### ISSUE TITLE
Users are omitted when UserName contains session ID digits, SessionName trimmed when starting with characters in UserName

### ISSUE THREAD

**Issue by mrweir** [UNT-CAS/QuserObject#13]
Hello,

I found a bug where a user is omitted from the output entirely if their username contains the digits of their session ID, and an error is returned as well.  This is because TrimStart will trim the characters provided in any order, with any number of repetitions until it hits a non-matching character.  So if a user's session ID is 22 and their username has 2 in it, it breaks things.
The same problem causes the SessionName to be trimmed excessively as well when the SessionName starts with any characters contained in the UserName.
I've submitted a pull request (#12) which should fix this problem.

Thanks!

**Comment by VertigoRay** [comment]
Thanks for the PR!
