### ISSUE TITLE
Users with Spaces in SamAccountName break output

### ISSUE THREAD

**Issue by Yevrag35** [UNT-CAS/QuserObject#6]
FYI, this is a fringe case.  Just bringing it up for awareness.

If you have an AD (or local) user account with SamAccountName that includes 'multiple' spaces within the space, the output is broken.  One space seems to be ok.  The output is **not** broken when the user with multiple spaces is 'disconnected', but the 2nd half of the name will show in the SessionName.

![image](https://user-images.githubusercontent.com/20248838/91743571-03326200-eb86-11ea-85e3-618d1f09d84e.png)

If the user logs in though, the output breaks as it has already interpreted the SessionName header:
![image](https://user-images.githubusercontent.com/20248838/91743630-19d8b900-eb86-11ea-92eb-7a359ddf0637.png)

### Resolution

Obviously, to fix this would require adding into the regex to check for more spaces... but how many?  My proposal would, instead, be to look at Regex **AND** the index that is returned from to build headers and then match any text in between those indexes.  In my private tests, this seemed to work... though it took a complete re-working of the code to do so:

![image](https://user-images.githubusercontent.com/20248838/91743943-a8e5d100-eb86-11ea-9940-4caf63b60531.png)

**Comment by VertigoRay** [comment]
Wow ...  I've never used `SamAccountName` with any spaces, and I've never considered a `SamAccountName`  with multiple spaces.

I'm fine with re-working to improve functionality. Can you provide a sample of the code the worked for you so I don't have to start from scratch, please?

**Comment by VertigoRay** [comment]
Right now, my mind is going towards comparing each row with `(Get-CimInstance Win32_LoggedOnUser).Antecedent.Name | Select -Unique`. This would allow me to add a Domain ...

Of course, then we'd have to deal with the fringe case of a local account with the same name as a domain account being logged in within the same couple of minutes. 😏 

Just thinking out loud here ...

```powershell
$quserRow = '>vertigo  ray              rdp-tcp#71          5  Active          .  11/16/2020 8:46 AM'

# filter down possible logon sessions
$logonSessions = Get-CimInstance Win32_LogonSession
$logonSessionsTyped = $logonSessions | ?{ $_.LogonType -in @(2,10)}
$possibleSessions = Get-CimInstance Win32_LoggedOnUser | ?{ $_.Dependent.LogonId -in ($logonSessionsTyped).LogonId } | Select-Object @(@{n='Name';e={$_.Antecedent.Name}},@{n='Domain';e={$_.Antecedent.Domain}},@{n='LogonType';e={$id = $_.Dependent.LogonId; ($logonSessions | ?{ $_.LogonId -eq $id }).LogonType}},@{n='StartTime';e={$id = $_.Dependent.LogonId; ($logonSessions | ?{ $_.LogonId -eq $id }).StartTime}})

# quser doesn't give me seconds
$quserLogonTime = Get-Date ($quserRow -split '\s{2,}')[-1]

# give me sessions within a minute of the quser logon time.
$probableSessions = $possibleSessions | ?{ ($_.StartTime.AddMinutes(-1) -lt $quserLogonTime) -and ($_.StartTime.AddMinutes(1) -gt $quserLogonTime) }

# Find the match:
$probableSessions | ?{ $quserRow.TrimStart('>').Trim().StartsWith($_.Name, 'CurrentCultureIgnoreCase') }
```

I could then strip the username off the start, the logon time off the end, and process the rest of the columns as always. 😅

**Comment by VertigoRay** [comment]
As I was laying down last night, I realized that my previous comment introduces issues with remote `quser` lookups where WinRM would be required to collect the information from WMI. I then realized that I could do it simply by indexing backwards:

```powershell
$quserRow = '>vertigo  ray              rdp-tcp#71          5  Active          .  11/16/2020 8:46 AM'
$quserRowSplit = $quserRow.TrimStart('>') -split '\s{2,}'
$quserUserNameExists = $quserRow.TrimStart('>') -match ('^({0})' -f ($quserRowSplit[0..($quserRowSplit.Count-6)] -join '\s{2,}'))

$quser = @{
    IsCurrentSession = $quserRow.StartsWith('>')
    LogonTime = $quserRowSplit[-1]
    IdleTime = $quserRowSplit[-2]
    State = $quserRowSplit[-3]
    Id = $quserRowSplit[-4]
    SessionName = $quserRowSplit[-5]
    UserName = $matches[1]
}
```

In my testing, it doesn't matter if it's 2 spaces:

```powershell
PS > $quser

Name                           Value
----                           -----
Id                             5
State                          Active
IdleTime                       .
LogonTime                      11/16/2020 8:46 AM
UserName                       vertigo  ray
IsCurrentSession               True
SessionName                    rdp-tcp#71
```

Or 10 spaces:

```powershell
PS > $quserRow = '>vertigo          ray              rdp-tcp#71          5  Active          .  11/16/2020 8:46 AM'
...
PS > $quser

Name                           Value
----                           -----
Id                             5
State                          Active
IdleTime                       .
LogonTime                      11/16/2020 8:46 AM
UserName                       vertigo          ray
IsCurrentSession               True
SessionName                    rdp-tcp#71
```

Or a really odd username:

```powershell
PS > $quserRow = '>v er       tigo  ray              rdp-tcp#71          5  Active          .  11/16/2020 8:46 AM'
...
PS > $quser

Name                           Value
----                           -----
Id                             5
State                          Active
UserName                       v er       tigo  ray
SessionName                    rdp-tcp#71
IsCurrentSession               True
IdleTime                       .
LogonTime                      11/16/2020 8:46 AM
```

Without breaking a *standard* username:

```powershell
PS > $quserRow = '>vertigoray              rdp-tcp#71          5  Active          .  11/16/2020 8:46 AM'
...
PS > $quser

Name                           Value
----                           -----
Id                             5
State                          Active
UserName                       vertigoray
SessionName                    rdp-tcp#71
IsCurrentSession               True
IdleTime                       .
LogonTime                      11/16/2020 8:46 AM
```

**Comment by VertigoRay** [comment]
Final fix involved a bit more fitness with the length of the username header and taking the same amount of space off of each row for the username. Then, I could reliable treat two or more spaces as column separators for the rest of the columns.
