### ISSUE TITLE
Incorrect output for IdleTime

### ISSUE THREAD

**Issue by JamesHorsley** [UNT-CAS/QuserObject#7]
Sometimes I am seeing strange values for IdleTime such as:

IdleTime    : 24692.13:29:00

With the IdleStartTime switch it shows a sensible value so this looks like some parsing issue on the QUser output.  It seems to show these odd values when the sessions has only been idle a very short time.

**Comment by VertigoRay** [comment]
Can you show me a comparison between `quser` and `Get-Quser -Debug`? Without knowing what the *stdout* value is, it's impossible for me to troubleshoot.

**Comment by JamesHorsley** [comment]
OK - battled to get this to repeat - then remembered I was doing it from another server when I saw issue ... for same remote server using `quser` itself I see this when run from a Windows Server 2008R2 box:

```
 user1              rdp-tcp#1          30  Active          .  12/11/2020 11:23
 user2             rdp-tcp#111        42  Active  24692+13:29  16/11/2020 08:58
 user3              rdp-tcp#88         55  Active          8  17/11/2020 12:08
```

Same set of users when run from Windows Server 2019 box:

```
 user1              rdp-tcp#1          30  Active          1  12/11/2020 11:23
 user2             rdp-tcp#111        42  Active          .  16/11/2020 08:58
 user3              rdp-tcp#88         55  Active         14  17/11/2020 12:08
```

So it looks like it is some difference in how old `quser` output stuff - could well be a bug in `quser`!  Because user is supposedly active so can't see how they have been idle like that - perhaps a bug in old `quser` if user logged on for days like this.

**Comment by VertigoRay** [comment]
I appreciate you following up. I agree, it doesn't appear to be an issue with parsing the output.
