### ISSUE TITLE
Unable to specify username, sessionname or sessionid

### ISSUE THREAD

**Issue by JamesHorsley** [UNT-CAS/QuserObject#8]
The actual QUser command allows this format:

QUERY USER [username | sessionname | sessionid] [/SERVER:servername]

The username option of this in particular is quite useful to find where a particular user is logged in to on an RDP Farm or when you have had a lot of RDP sessions and your connection drops so you want to find all the places you were connected to again.  Perhaps extra parameters like -UserName, -SessionName and -SessionId could be added (though these should be mutually exclusive) or just a single parameter to pass through to QUser which itself does not distinguish between the 3 - but choosing a name for that could be tricky!

**Comment by JamesHorsley** [comment]
If you check my pull request I have added support for this

**Comment by VertigoRay** [comment]
Nice, thanks. Taking a look.

**Comment by VertigoRay** [comment]
Honored to approve your first PR; just waiting for the checks to complete. Thanks for the assist. 😁
